import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { api } from '../../lib/api';

type Customer = { _id: string; name: string };
type Item = { description: string; quantity: number; unitPrice: number; taxRate: number };
export default function InvoiceCreate() { const nav = useNavigate(); const [params] = useSearchParams(); const [customers, setCustomers] = useState<Customer[]>([]); const [customerId, setCustomerId] = useState(''); const [items, setItems] = useState<Item[]>([{ description: '', quantity: 1, unitPrice: 0, taxRate: 19.25 }]); const [error, setError] = useState(''); const type = params.get('type') === 'quote' ? 'quote' : params.get('type') === 'credit_note' ? 'credit_note' : 'invoice'; useEffect(() => { api<Customer[]>('/invoicing/customers').then(setCustomers).catch(e => setError(e.message)); }, []);
  function update(index: number, key: keyof Item, value: string) { setItems(items.map((item, i) => i === index ? { ...item, [key]: key === 'description' ? value : Number(value) } : item)); }
  async function submit(e: FormEvent) { e.preventDefault(); try { const result = await api<{ _id: string }>('/invoicing', { method: 'POST', body: JSON.stringify({ type, customerId, items }) }); nav(`/billing/invoices/${result._id}`); } catch (e) { setError(e instanceof Error ? e.message : 'Erreur'); } }
  const total = items.reduce((sum, item) => sum + item.quantity * item.unitPrice * (1 + item.taxRate / 100), 0);
  return <form onSubmit={submit} className="mx-auto max-w-4xl space-y-6"><div className="flex items-center gap-3"><Link to="/billing" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={20} /></Link><div><p className="text-sm font-semibold uppercase tracking-widest text-emerald-600">Nouveau document</p><h1 className="text-3xl font-black">{type === 'quote' ? 'Nouveau devis' : type === 'credit_note' ? 'Nouvel avoir' : 'Nouvelle facture'}</h1></div></div>{error && <div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><label className="label">Client</label><select required value={customerId} onChange={e => setCustomerId(e.target.value)} className="field mt-2 w-full"><option value="">Sélectionner un client</option>{customers.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}</select></section><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Lignes</h2><button type="button" onClick={() => setItems([...items, { description: '', quantity: 1, unitPrice: 0, taxRate: 19.25 }])} className="inline-flex items-center gap-1 text-sm font-bold text-emerald-600"><Plus size={16} /> Ajouter</button></div><div className="space-y-3">{items.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_90px_130px_90px_32px]"><input required placeholder="Description" value={item.description} onChange={e => update(index, 'description', e.target.value)} className="field" /><input required type="number" min="1" value={item.quantity} onChange={e => update(index, 'quantity', e.target.value)} className="field" /><input required type="number" min="0" value={item.unitPrice} onChange={e => update(index, 'unitPrice', e.target.value)} className="field" /><input type="number" min="0" value={item.taxRate} onChange={e => update(index, 'taxRate', e.target.value)} className="field" /><button type="button" title="Supprimer" disabled={items.length === 1} onClick={() => setItems(items.filter((_, i) => i !== index))} className="text-slate-400 disabled:opacity-30"><Trash2 size={17} /></button></div>)}</div><div className="mt-6 flex justify-end border-t border-slate-200 pt-4 text-lg font-black dark:border-slate-800">Total estimé : {new Intl.NumberFormat('fr-CM', { style: 'currency', currency: 'XAF', maximumFractionDigits: 0 }).format(total)}</div></section><div className="flex justify-end"><button className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">Créer le document</button></div></form>;
}
