export enum Permission {
  COMPANY_READ = 'company:read',
  COMPANY_UPDATE = 'company:update',
  USERS_READ = 'users:read',
  USERS_CREATE = 'users:create',
  USERS_UPDATE = 'users:update',
  USERS_DELETE = 'users:delete',
  INVOICE_READ = 'invoice:read',
  INVOICE_CREATE = 'invoice:create',
  INVOICE_UPDATE = 'invoice:update',
  INVOICE_DELETE = 'invoice:delete',
  CRM_READ = 'crm:read',
  CRM_CREATE = 'crm:create',
  CRM_UPDATE = 'crm:update',
  STOCK_READ = 'stock:read',
  STOCK_CREATE = 'stock:create',
  STOCK_UPDATE = 'stock:update',
  HR_READ = 'hr:read',
  HR_CREATE = 'hr:create',
  HR_UPDATE = 'hr:update',
  PROJECT_READ = 'project:read',
  PROJECT_CREATE = 'project:create',
  PROJECT_UPDATE = 'project:update',
  ECOMMERCE_READ = 'ecommerce:read',
  ECOMMERCE_CREATE = 'ecommerce:create',
  ECOMMERCE_UPDATE = 'ecommerce:update',
}
